# Generated by Django 5.2.1 on 2025-10-09 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Helmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_c', models.DecimalField(decimal_places=1, max_digits=5)),
                ('gas_ppm', models.IntegerField()),
                ('pulse_bpm', models.IntegerField()),
                ('battery_pct', models.IntegerField()),
                ('rssi_dbm', models.IntegerField()),
                ('alerts_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('helmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.helmet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
